### ISSUE TITLE
The task is being canceled

### ISSUE THREAD

**Issue by rinrinx2** [sentinm/Rclone-Heroku#1]
While normally needs to work 24 hours in. The task is being canceled after a time when copying.

Can you make it work for 24 hours?

**Comment by sentinm** [comment]
> While normally needs to work 24 hours in. The task is being canceled after a time when copying.
> 
> Can you make it work for 24 hours?

Oh, can you send the log of your application?

**Comment by rinrinx2** [comment]
bro it doesn't give an error in the log.
i want to describe the error like this

For example, when copying from one iCloud to another iCloud, the task is interrupted.

Let's say you transferred 1000 files, after sending 800 files, the task ends.  probably this problem is related to the application not working properly

**Comment by rinrinx2** [comment]
github workflow is not working after yesterday's update bro.  I have tested

**Comment by sentinm** [comment]
> bro it doesn't give an error in the log.
> i want to describe the error like this
> 
> For example, when copying from one iCloud to another iCloud, the task is interrupted.
> 
> Let's say you transferred 1000 files, after sending 800 files, the task ends. probably this problem is related to the application not working properl

Well, I never tried copying 1000+ files but this could be a problem with rclone or the storage client try searching for their support forums for the problem.(I'll too)

>github workflow is not working after yesterday's update bro. I have tested

![Screenshot_2022-02-14-08-06-23_1366x768](https://user-images.githubusercontent.com/79321771/153884616-62e2232e-7019-4868-ac3d-b3e73e9f3a43.png)

Your Heroku app's name is incorrect, check it and re-run the workflow!

**Comment by rinrinx2** [comment]
no bro, this is not related to rclone, another friend of mine made rclone ui.  it works on heroku, i copied 750gb nonstop.

**Comment by rinrinx2** [comment]
2022-02-14T17:07:49.399020+00:00 heroku[web.1]: Starting process with command `node getconf.js`
2022-02-14T17:07:50.641178+00:00 app[web.1]: [Std Error] curl: (3) <url> malformed
2022-02-14T17:07:50.641188+00:00 app[web.1]:   % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
2022-02-14T17:07:50.641188+00:00 app[web.1]:                                  Dload  Upload   Total   Spent    Left  Speed
2022-02-14T17:07:50.641188+00:00 app[web.1]: 
2022-02-14T17:07:50.641189+00:00 app[web.1]: 
2022-02-14T17:07:50.945822+00:00 heroku[web.1]: State changed from starting to crashed
2022-02-14T17:07:50.744761+00:00 heroku[web.1]: Process exited with status 0


Workflow Problem

**Comment by sentinm** [comment]
Check if `CONFIG_FILE_URL` var in your heroku app is a url and it is added correctly.

**Comment by sentinm** [comment]
> no bro, this is not related to rclone, another friend of mine made rclone ui.  it works on heroku, i copied 750gb nonstop.

Well `rclone-web-gui` is kinda buggy and I'm looking forward for adding `rclone-ng` for this after testing it. If you know any other opensource ui's for rclone. Please let me know.

**Comment by rinrinx2** [comment]
@sentinm do you have a telegram

**Comment by sentinm** [comment]
> @sentinm do you have a telegram 

same username.
