### ISSUE TITLE
Create a docker compose file 

### ISSUE THREAD

**Issue by bolavefasfas** [sentinm/Rclone-Heroku#4]

**Comment by sentinm** [comment]
Can you explain a bit? like for which platform's deployment or ...?

**Comment by rinrinx2** [comment]
bro it would be great if you add google colab support

**Comment by sentinm** [comment]
> bro it would be great if you add google colab support

ok I'll do it

**Comment by rinrinx2** [comment]
thank yo so much

**Comment by bolavefasfas** [comment]
> Can you explain a bit? like for which platform's deployment or ...?

Selfhosting
